spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
#          打开根据服务的serviceId来匹配路由
          enabled: false
#          请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          lower-case-service-id: true

      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path= /system/**
#         在转发之前将/system去掉
          filters:
            - StripPrefix=1

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/






